apiVersion: v1
kind: Service
metadata:
  labels:
    app: pnb-demo-1
  name: pnb-demo-1
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: pnb-demo-1
