apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend-ms
  name: backend-ms
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: backend-ms
